FROM debian:stretch-slim

RUN apt-get update

RUN apt-get install -y \ 
    curl \
    apt-transport-https \ 
    lsb-release \ 
    gnupg
RUN curl -sL \
    https://deb.nodesource.com/setup_8.x \
    -o nodesource_setup.sh && \
    bash nodesource_setup.sh

RUN apt-get install -y \
    nodejs \
    build-essential \
    git-all

RUN apt-get update

RUN curl https://cli-assets.heroku.com/install.sh | sh

RUN apt-get update && \ 
    apt-get autoclean && \ 
    apt-get autoremove

RUN npm install -g \
    npm@6.2.0 \
    typescript \
    nodemon

EXPOSE 3000

RUN useradd -r -m estudiante --uid 1000

RUN mkdir /home/estudiante/project

RUN chmod -R 777 /home/estudiante/project

USER estudiante

WORKDIR /home/estudiante/project
